[tools]
python = "3.13"
uv = "0.11.14"
cmake = "4.3.3"
ninja = "1.13.2"
sentry-cli = "3.6.1"

[tasks.build]
description = "Build Qt artifacts"
env = { PYTHONUNBUFFERED = "1" }
run = [
	"uv run --locked --python 3.13 python -u ./build.py",
]

[tasks.upload-symbols]
description = "Upload Qt/PySide debug symbols to Sentry"
env = { PYTHONUNBUFFERED = "1" }
run = [
	"python -u ./upload_symbols.py",
]
